apiVersion: apps/v1
kind: Deployment
metadata:
  name: uwsgi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: uwsgi-operator
  template:
    metadata:
      labels:
        name: uwsgi-operator
    spec:
      containers:
        - name: uwsgi-operator
          image: sjonessot/uwsgi-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - uwsgi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "uwsgi-operator"
